Working form submit
SergeGray/vue-course pull request #2
Opened 2020-11-19 11:59 UTC by SergeGray

2020-11-20 19:54 UTC, IgorShayderov requested changes

2020-11-20 19:54 UTC, IgorShayderov commented on task2-2/index.html
> +        <form @submit.prevent="formSubmitted = true" v-if="!formSubmitted">
Чтобы было лучше читать код когда атрибутов много, надо располагать каждый атрибут на отдельной строке.

2020-11-20 19:54 UTC, IgorShayderov commented on task2-2/index.html
> +<!doctype html>
Ты хоть отступы в виде пустых строк делай между некоторыми блоками, чтобы проще было читать код, а то все это превращается в кашу.

2020-11-20 19:54 UTC, IgorShayderov commented on task2-2/index.html
> +          <template v-show="!fieldsHidden">
Это тут точно должно быть?

2020-11-20 19:54 UTC, IgorShayderov commented on task2-2/index.html
> +                       value="Phone"
Ты используешь v-model, который и так связывает инпут со значением, так что этот value будет игнорироваться.

2020-11-20 19:54 UTC, IgorShayderov commented on task2-2/index.html
> +              <label>Send me spam</label>
Этот label не связан ни с каким инпутом, так что он не оправдывает свой семантический смысл, надо его либо связать, либо использовать другой тэг.

2020-11-20 19:54 UTC, IgorShayderov commented on task2-2/index.html
> +                       value="Email"
Анологично тому что выше

2020-11-20 19:54 UTC, IgorShayderov commented on task2-2/index.html
> +          <tr v-for="(value, option) in pickedOptions">
v-for требует указать :key для того чтобы элементы были уникальными, иначе Vue не поймет что это разные элементы, из-за чего могут быть проблемы, по идее в консоле должен быть warning из-за этого.

2020-11-20 19:54 UTC, IgorShayderov commented on task2-2/index.html
> +          options: {
Слишком общее название свойства, можно было бы конкретизировать что это за опции.

2020-11-20 19:54 UTC, IgorShayderov commented on task2-2/index.html
> +            if (
Тяжело читать код с такими условиями, если условие слишком длинное, то его лучше вынести в отдельную переменную. По крайней мере операцию вычитания.
Можно использовать деструктуризацию объекта:
const { target } = event;
(обычно мы используем const, когда не собираемся изменять значение и let в противном случае)

2020-11-20 19:54 UTC, IgorShayderov commented on task2-2/index.html
> +              let { spamPlatform, ...optionsWithoutPlatform } = this.options
А зачем ты тут декструктурируешь spamSpatform, если ты его не используешь?
Плюс с optionsWithoutPlatform - фигня какая-то, деструктуризация + rest, удивительно что это работает. Я проверил в sandbox и получилось что при такой деструктуризации возвращается сам же объект, то есть она вообще не имеет никакого смысла.

2020-11-20 19:54 UTC, IgorShayderov commented on task2-2/index.html
> +            if (this.options.sendSpam) {
Можно было бы деструктурировать сразу, а потом использовать тернарный оператор и получилось бы более компактно:
const { sendSpam, optionsWithoutPlatform } = this.options;

return sendSpam ? this.options : optionsWithoutPlatform;

2020-11-21 07:22 UTC, SergeGray commented on task2-2/index.html
> +                       value="Phone"
Будет игнорироваться name, а не value, а так да, ты прав.

2020-11-21 07:39 UTC, SergeGray commented on task2-2/index.html
> +              let { spamPlatform, ...optionsWithoutPlatform } = this.options
У меня получается что optionsWithoutPlatform зто options, но без ключа spamPlatform. Взял это решение со StackOverflow.

2020-11-21 07:41 UTC, SergeGray commented on task2-2/index.html
> +          <template v-show="!fieldsHidden">
Там задание было, что после scroll'а должны появиться чекбоксы, но я использовал template с v-show, поэтому у меня ничего не происходило, а я не заметил.

2020-11-21 07:42 UTC, SergeGray commented on task2-2/index.html
> +          <tr v-for="(value, option) in pickedOptions">
У такого простого объекта vue сам вроде ставит ключи.

2020-11-21 09:21 UTC, IgorShayderov commented on task2-2/index.html
> +              let { spamPlatform, ...optionsWithoutPlatform } = this.options
Понял. Вряд ли кто-то поймет такое без гугла, похоже на хак) Если у тебя какое-то свойство оказалось лишним, то скорее всего его там не должно было быть.

2020-11-21 09:21 UTC, IgorShayderov commented on task2-2/index.html
> +                       value="Phone"
Почему name? v-model связывает двусторонней связью атрибут value

2020-11-21 09:24 UTC, IgorShayderov commented on task2-2/index.html
> +          <template v-show="!fieldsHidden">
Что за template? Ты с React'ом перепутал что ли?

2020-11-21 09:54 UTC, SergeGray commented on task2-2/index.html
> +          <template v-show="!fieldsHidden">
https://vuejs.org/v2/guide/conditional.html?#Conditional-Groups-with-v-if-on-lt-template-gt

2020-11-21 09:56 UTC, SergeGray commented on task2-2/index.html
> +                       value="Phone"
Я в value пишу значение, которое будет у аттрибута если выбрать этот radio box. а name это для группинга боксов, но я потестил и он вроде не нужен.

2020-11-21 09:59 UTC, SergeGray commented on task2-2/index.html
> +              let { spamPlatform, ...optionsWithoutPlatform } = this.options
В задании форма на вывод в таком виде, что если sendSpam === false, то платформа вообще не выводится.

2020-11-21 17:22 UTC, IgorShayderov commented on task2-2/index.html
> +          <template v-show="!fieldsHidden">
Прочитал что ты скинул -

>  Note that v-show doesn’t support the <template> element, nor does it work with v-else.

2020-11-21 17:32 UTC, IgorShayderov commented on task2-2/index.html
> +                       value="Phone"
Если ты уберешь name, то радио-кнопки станут отдельными и можно будет их все включать вместо одной на группу. Я тебе говорю что не использовать атрибут value т.к. v-model уже сам это делает. v-model это синтаксический сахар, в данном случае он объединяет:
:value="agreementOptions.spamPlatform"
@input="agreementOptions.spamPlatform = $event" (или $event.target.value, не помню)
То есть то что ты ещё дополнительно к этому делаешь присвоение атрибута `value="Phone"` не делает ничего

2020-11-21 17:50 UTC, SergeGray commented on task2-2/index.html
> +                       value="Phone"
Так мне же нужно как-то передать через radio button значение 'Phone' в этот аттрибут.  Я это из документации взял https://vuejs.org/v2/guide/forms.html#Radio

2020-11-21 17:50 UTC, SergeGray commented on task2-2/index.html
> +          <template v-show="!fieldsHidden">
Я про это и говорил, я его уже поменял на div

2020-11-22 15:16 UTC, IgorShayderov approved these changes

2020-11-22 15:16 UTC, IgorShayderov commented on task2-2/index.html
> +                       value="Phone"
Тогда ты прав, я не посмотрел что это радио

2020-11-22 15:17 UTC, merged