Add transitions
SergeGray/vue-course pull request #7
Opened 2020-11-25 10:08 UTC by SergeGray

2020-11-25 19:55 UTC, IgorShayderov requested changes

2020-11-26 12:14 UTC, SergeGray commented on task5/src/App.vue
> +  .fade-enter {
fade-enter отрабатывает первым и ставит 0, потом у меня в fade-enter-active не opacity, как ты сказал, а transition: opacity 0.5s.

2020-11-26 12:20 UTC, SergeGray commented on task5/src/components/MultipleAnswersQuestion.vue
> +      this.selectedAnswers = this.answers.map(() => false);
При создании элемента я делаю вот это вот для того, чтобы просто создать массив нужной длины. Я решил хранить массив с выбраными чекбоксами в дате компонента. При сабмите формы он отправляется обработчику, а при перезагрузке компонента сбрасывается обратно на [false, false, false]. Я не сделал его просто массивом длины 4 на случай, если ответов в вопросе будет больше или меньше.

2020-11-26 12:24 UTC, SergeGray commented on task5/.gitignore
> +npm-debug.log*
Наверное можно, этот файл сделался автоматически, я его не менял.

2020-11-26 12:24 UTC, SergeGray commented on task5/.gitignore
> +.idea
Я просто сделал `vue create task5`

2020-11-26 12:24 UTC, SergeGray commented on task5/src/components/SingleAnswerQuestion.vue
> +             @input="answered = true">
В принципе всё работало, но я поменял.

2020-11-26 16:06 UTC, IgorShayderov commented on task5/src/components/MultipleAnswersQuestion.vue
> +      this.selectedAnswers = this.answers.map(() => false);
Вообще это похоже на "костыль". Можно тогда уж добавить в дате атрибут defaultValues: [false, false, false, false] и это значение можно сразу selectedAnswers присвоить.

2020-11-26 16:13 UTC, SergeGray commented on task5/src/App.vue
> +  .fade-enter {
Делал точно по гайду из видеоурока, без этого класса они меняются мгонвенно и нет никакого тринзишна. Вся идея в том, чтобы добавить анимацию.

2020-11-26 16:18 UTC, SergeGray commented on task5/src/components/MultipleAnswersQuestion.vue
> +      this.selectedAnswers = this.answers.map(() => false);
Для конкретно этого примера это сработает, но если я захочу сделать вопрос с двумя ответами, или с восемью, то придется переделывать. Этот метод быстрее, чем `Array(length).fill(false);`

2020-11-27 14:19 UTC, IgorShayderov approved these changes

2020-11-29 09:41 UTC, merged